### ISSUE TITLE
Not all resources created

### ISSUE THREAD

**Issue by nuriaruiz** [Azure/AOAI-workshop#11]
I'm following the instructions outlined in the "Requirements" section, and after creating my Azure account, I uploaded the two files, createAll.ps1 and deployAll.bicep. Subsequently, I executed the script ./createAll.ps1, but encountered errors in the shell:

Error: Code=SpecialFeatureOrQuotaIdRequired; Message=The subscription does not have QuotaId/Feature required by SKU 'S0' from kind 'OpenAI' or contains blocked QuotaId/Feature.

Currently, I can only see the following resources created:
![image](https://github.com/Azure/AOAI-workshop/assets/14306331/34981856-395f-4e08-992d-9c056747a497)

I'm uncertain whether my current Azure subscription, which is the free temporary subscription, meets the requirements for the services I'm trying to use.

Is there any additional information needed to resolve this error, or any steps I should take to ensure the successful deployment of the resources? Thank you so much for your help.

**Comment by frsl92** [comment]
Hello @nuriaruiz. 

You need to apply for access to Azure OpenAI on your subscription. Please check [this](https://customervoice.microsoft.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7en2Ais5pxKtso_Pz4b1_xUNTZBNzRKNlVQSFhZMU9aV09EVzYxWFdORCQlQCN0PWcu).

**Comment by nuriaruiz** [comment]
Thanks @frsl92
